### ISSUE TITLE
 pagedSuggestions.at is not a function on WSL2, node14

### ISSUE THREAD

**Issue by ilovejs** [microsoft/inshellisense#14]
Straight after install with node v14.21.3
crash

```
➜  Code inshellisense --shell zsh

  ERROR  pagedSuggestions.at is not a function

 file:///home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/build/ui/suggestions.js:48:
 48

 -Suggestion (file:///home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/build/ui/sugge
            stions.js:48:48)
 -renderWithHoo (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/react
  s            -reconciler/cjs/react-reconciler.development.js:7478:18)
 -mountIndeterminateComp (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modu
  nent                  les/react-reconciler/cjs/react-reconciler.development.js:11247:13)
 -beginWork (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/react-rec
           onciler/cjs/react-reconciler.development.js:12760:16)
 -beginWork$ (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/react-re
            conciler/cjs/react-reconciler.development.js:19569:14)
 -performUnitOfWo (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/rea
  k              ct-reconciler/cjs/react-reconciler.development.js:18703:12)
 -workLoopSyn (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/react-r
             econciler/cjs/react-reconciler.development.js:18609:5)
 -renderRootSyn (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/react
               -reconciler/cjs/react-reconciler.development.js:18577:7)
 -performSyncWorkOnR (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/
  ot                react-reconciler/cjs/react-reconciler.development.js:18193:20)
 -flushSyncCallbac (/home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/re
  s               act-reconciler/cjs/react-reconciler.development.js:2936:22)

The above error occurred in the <Suggestions> component:

    at Suggestions (file:///home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/build/ui/suggestions.js:42:39)
    at ink-box
    at Box (file:///home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/ink/build/components/Box.js:5:27)
    at UI (file:///home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/build/ui/ui-root.js:11:15)
    at InternalApp (file:///home/ilovejs/.nvm/versions/node/v14.21.3/lib/node_modules/@microsoft/inshellisense/node_modules/ink/build/components/App.js:19:9)

React will try to recreate this component tree from scratch using the error boundary you provided, InternalApp.
➜  Code node -v
v14.21.3
```

**To Reproduce**
install
run like above

**Expected behavior**

**Environment**
 - OS: win11+inside WSL2
 - Output of `inshellisense --version`:  0.0.1-rc.1
 - Nodejs Version: v14.21.3

**Additional context**

**Comment by gscragg-lawvu** [comment]
According to [Mozilla Docs](https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/at#browser_compatibility), that function needs node 16.6.0
