### ISSUE TITLE
does not work on ubuntu 22.04 + bash: SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by kforner** [microsoft/inshellisense#33]
**Describe the bug**

```
sudo apt install npm
sudo npm install -g @microsoft/inshellisense
▶ inshellisense --shell bash
file:///usr/local/lib/node_modules/@microsoft/inshellisense/build/index.js:14
    .version(await getVersion(), "-v, --version", "output the current version")
             ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

```
**Environment**
 - OS: ubuntu 22.04
 - Output of `inshellisense --version`: it crashes
 - Nodejs Version: v12.22.9

**Comment by cpendery** [comment]
Hi @kforner, as mentioned in the readme, inshellisense requires Node 16.x or higher. Please try upgrading your node version

**Comment by kforner** [comment]
ok thanks

**Comment by kforner** [comment]
works now.
